### ISSUE TITLE
Upgrade of Elasticsearch

### ISSUE THREAD

**Issue by markwalkom** [morucci/repoxplorer#28]
G'Day!
I was wondering if you would be open to upgrading to Elasticsearch 6.X? I'd be happy to provide some assistance(/expertise) where I can.

**Comment by morucci** [comment]
Hi,

Yes sure, it makes sense to me to follow last versions of lib/services on which repoXplorer is based. The test suite relies on a running ElasticSearch instance so we can see pretty quickly which features are broken with version 6 and/or need adaptation.
I'll give it a try when I'll have time so thank I appreciate your help proposal :)
I see you're part of the Elastic organization on Github so you might also be interested that the demo node of the project indexes the Elastic organization. http://5.135.161.134/repoxplorer-demo/project.html?pid=elastic

Thanks for your interest to this project.

**Comment by markwalkom** [comment]
I have seen that instance, thanks for hosting that :D

It's why I thought I'd make the offer to upgrade the version, to see what other interesting things we may be able to extract from the data with newer versions.

**Comment by morucci** [comment]
Since https://github.com/morucci/repoxplorer/commit/1ec77c58f6e49198bea2717c4ab42fcdf115e055 repoxplorer support ElasticSearch 5.X and 6.X. Indexes needs to be deleted and project re-indexed.
