### ISSUE TITLE
Github Enterprise Support with AD authentication

### ISSUE THREAD

**Issue by hbajaj2** [morucci/repoxplorer#32]
Is there an option to use this explorer against Github enterprise with AD authentication. Kindly suggest possible ways to make it work.

**Comment by morucci** [comment]
Hi, no but repoxplorer only needs access the to the git repos whatever it is github enterprise or a regular git server. The issue here seems to be the authentication. You may be able to set valid credential in https://github.com/morucci/repoxplorer/blob/master/bin/repoxplorer-git-credentials-helper

**Comment by hbajaj2** [comment]
Thanks @morucci , I am able to fetch org and repo by using github3:GithubEnterprise method and able to provide url and personal access token against GHE, but the indexerDaemon within the container is failing 
stating "_Password authentication is not available for git operations, one must use personal access token or ssh_". Is there any option to provide personal access token via credential helper method.

**Comment by morucci** [comment]
@hbajaj2, oh ok you were talking about bin/repoxplorer-github-organization ... do not hesitate to propose a PR then :) (I don't have access to a github enterprise deployment).
Regarding the Indexer, let me know if this help: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/ as it seems using the token in place of the password could work.

**Comment by morucci** [comment]
Recently some changes have been merged regarding authentication especially on Github. https://github.com/morucci/repoxplorer#index-a-github-organization
I close the isse. Please re-open if that does not work for you.
