### ISSUE TITLE
Getting permission issues after adding token

### ISSUE THREAD

**Issue by duffybelfield** [morucci/repoxplorer#51]
After using the --token parameter on

`repoxplorer-github-organization --org xxx --skip-fork --output-path /etc/repoxplorer/defs/xxx --token xxxxxx`

I'm still seeing authentication issues "Username and Password wrong", shouldn't I only need the token for private repos?

`Invalid username or password.\nfatal: Authentication failed for 'https://github.com/xxx/xxx/`

**Comment by morucci** [comment]
Hi, If I understand well you succeeded to use repoxplorer-github-organization with --token to create the description file. right ?
Then It fail at indexation with authentication issue. In that case you need to use the same token as password for the credential helper https://github.com/morucci/repoxplorer#private-repositories
