### ISSUE TITLE
Setup for GitHub Enterprise Server

### ISSUE THREAD

**Issue by PramodhMDT** [morucci/repoxplorer#56]
May I Know how to configure it for Enterprise Server

**Comment by morucci** [comment]
repoxplorer is using git repositories as data source. So as long as you can access them it should work w/o specific settings.
I also invite you to have a look to https://github.com/change-metrics/monocle, a new project I'm working on that provide Pull-Request related metrics (using the github api).  You may be interested. See the demo node: https://demo.changemetrics.io/python?gte=2015-01-01

**Comment by PramodhKumarM** [comment]
Thanks for the suggestion @morucci 

How to add all branches in YAML File, in an efficient way.
And how to add the multiple organizations when the owner of an organization is different,
Is there a way to add the multiple organizations in a single YAML File.

**Comment by PramodhMDT** [comment]
Thanks for the suggestion @morucci 

How to add all branches in YAML File, in an efficient way.
And how to add the multiple organizations when the owner of an organization is different,
Is there a way to add the multiple organizations in a single YAML File.

**Comment by morucci** [comment]
Hi @PramodhMDT https://github.com/morucci/repoxplorer#index-a-github-organization the repoxplorer-githhub-organization is made to fetch the organization's repos name + default branch from the github api and produce a yaml file that repoxplorer will use. You can run that tool multiple time to produce multiple yaml files (one by org), repoxplorer will read all yaml files it find in its config directory.
Regarding branches, the tool does not look for all branch names for each repo but instead the outputted file define a template that can be customized to defined additional branches you would to like to index.

**Comment by PramodhMDT** [comment]
Thanks for the response @morucci 

How to delete the existing index in container so that I should not see any data when I query in UI

**Comment by morucci** [comment]
You can list the indexes with:
```
docker-compose exec repoxplorer bash
curl -X GET "localhost:9200/_cat/indices"
```

Then delete each of them with:
```
for i in repoxplorer-projects repoxplorer-tags repoxplorer-users repoxplorer; do curl -X DELETE "localhost:9200/$i"; done
```

But IMO best is to, restart from scratch:
```
docker-compose down
rm -Rf docker-data
docker-compose up -d
```

**Comment by PramodhMDT** [comment]
Can we add the data that are pertained to UI like issue and pull request details.. 🤔 @morucci

**Comment by morucci** [comment]
repoxplorer datasource is git repositories only. I don't think I'll change that because it has the advantage to be generic and not tied to a platform like github or gitlab.
That's the point about the project I mentioned earlier https://github.com/change-metrics/monocle where datasource is the Pull-Request on Github or Review for Gerrit server.

**Comment by PramodhMDT** [comment]
I had a look at the monocle Repo.. @morucci 
Thank you 😊
