### ISSUE TITLE
Is there a way I can selectively disable the showing of commits by organization?

### ISSUE THREAD

**Issue by evangineer** [morucci/repoxplorer#58]
I've had an initial glance at `config.py` as well as looking at the documentation and it's not clear if it can be done and if so, how.

**Comment by morucci** [comment]
Hi, no this is not customizable through config.py.

**Comment by evangineer** [comment]
Okay, is there anyway I can selectively disable the commits at all?

**Comment by evangineer** [comment]
Overlaps with #59.  Closing.
