### ISSUE TITLE
Missing documentation/examples for indexer_skip_projects

### ISSUE THREAD

**Issue by evangineer** [morucci/repoxplorer#60]
What should it look like?

This?
`indexer_skip_projects = ['https://github.com/morucci/repoxplorer']`

Or this?
`indexer_skip_projects = ['morucci/repoxplorer']`

Or something else?

**Comment by evangineer** [comment]
Also what processes do I need to restart in order for this to be respected?

**Comment by morucci** [comment]
This is a list of Project names such as described here: https://github.com/morucci/repoxplorer#define-projects-to-index. Here project names are Barbican and Swift.
The repoxplorer-indexer service needs to restarted and then the indexer will skip all the repositories defined inside those 'excluded' projects.

Feel free to propose a PR to add an explanation/example in https://github.com/morucci/repoxplorer/blob/master/config.py

**Comment by evangineer** [comment]
Okay, thanks to your explanation it is clear that the scope of `indexer_skip_projects` is different from what I was looking for and needing.

Closing with thanks.
